services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe
      POSTGRES_PASSWORD: "jB8DEE5MCIWS2Wte2btjZeo0no2XeRBY"
    volumes:
      - magic_recipe_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "8hkxEeIwUMBDeu6nYgaPU8GjrmUMD1YA"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe_test
      POSTGRES_PASSWORD: "GcNlncYSiCz8v6PHgdTKFCqC4goDNyaT"
    volumes:
      - magic_recipe_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "rwn2KaNSRFUBZpqxpfChnwBMloc4d5-Y"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  magic_recipe_data:
  magic_recipe_test_data:
